---
- ros_topic_name: "/robot_1/diff_drive_controller/cmd_vel"
  gz_topic_name: "/mobile/diff_drive/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ


