- ros_topic_name: /sensors/towercrane/trolly_camera/color/camera_info
  gz_topic_name: /sensors/towercrane/trolly_camera/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: /sensors/towercrane/trolly_camera/points
  gz_topic_name: /sensors/towercrane/trolly_camera/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  gz_type_name: gz.msgs.PointCloudPacked
  direction: GZ_TO_ROS
