sensors: ["camera_pointcloud"]
camera_pointcloud:
    sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /robot_1/camera/depth/image_raw
    queue_size: 5
    near_clipping_plane_distance: 0.3
    far_clipping_plane_distance: 5.0
    shadow_threshold: 0.2
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: /robot_1/camera/filtered_points