joint_limits:
  joint_1:   # Slewing
      has_velocity_limits: true
      max_velocity: 0.17   # X10 rad/s (0.5 rpm)
      has_acceleration_limits: true
      max_acceleration: 0.1   # X10  

  joint_2:   # Pulling/Trolley
    has_velocity_limits: true
    max_velocity: 5.0   #X10  m/s
    has_acceleration_limits: true
    max_acceleration: 3.0  # X10 

  joint_3:
    has_velocity_limits: true
    max_velocity: 11.7   #X10  Hoisting
    has_acceleration_limits: true
    max_acceleration: 8.0  # X10 

  joint_4:
    has_velocity_limits: true
    max_velocity: 11.7
    has_acceleration_limits: true
    max_acceleration: 8.0

  joint_5:
    has_velocity_limits: true
    max_velocity: 11.7
    has_acceleration_limits: true
    max_acceleration: 8.0

  joint_6:
    has_velocity_limits: true
    max_velocity: 11.7
    has_acceleration_limits: true
    max_acceleration: 8.0

  joint_7:
    has_velocity_limits: true
    max_velocity: 11.7
    has_acceleration_limits: true
    max_acceleration: 8.0
